### ISSUE TITLE
Documentação das reutilizações no software

### ISSUE THREAD

**Issue by LimirioGuimaraes** [UnBArqDsw2024-1/2024.1_G2_My_Music#104]
### Summary

Redigir um documento apresentando pontos de reutilização no aplicativo.

### Motivation

A reutilização é um elemento importante na criação ágil de um software, para melhor localizar os leitores é ideal identificar quais elementos apresentam traços de reutilização.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MilenaBaruc** [comment]
Terminado
