### ISSUE TITLE
Diagrama de atividades

### ISSUE THREAD

**Issue by yabamiah** [UnBArqDsw2024-1/2024.1_G2_My_Music#32]
### Summary

Criação do artefato de modelagem de diagrama de atividades.

### Motivation

Diagrama de atividades é um tipo de diagrama que utiliza linguagem UML para dar destaque a processões, ações e eventos no sistema.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jvsoutomaior** [comment]
resolvido pela  [ PR #38 ](https://github.com/UnBArqDsw2024-1/2024.1_G2_My_Music/pull/38)
