### ISSUE TITLE
Diagrama de Componentes

### ISSUE THREAD

**Issue by LuisMiranda10** [UnBArqDsw2024-1/2024.1_G2_My_Music#35]
### Summary

Criação do artefato de modelagem de diagrama de componentes.

### Motivation

O diagrama de componente é um tipo de diagrama que mostra a estrutura do sistema de software, descrevendo os componentes do software, suas interfaces e suas dependências.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jvsoutomaior** [comment]
This issue is addressed by [PR #34 ](https://github.com/UnBArqDsw2024-1/2024.1_G2_My_Music/pull/34).
